import type { Beat } from "@/types";

export const MOCK_BEATS: Beat[] = [
  {
    id: "mock-1",
    beatmaker_id: "mock-producer",
    title: "Nuit Blanche",
    slug: "nuit-blanche",
    bpm: 140,
    key: "Am",
    genre: "Trap",
    tags: ["dark", "hard"],
    audio_preview_url: null,
    audio_full_url: null,
    cover_image_url: null,
    price_simple: 29.99,
    price_exclusive: 499.99,
    is_exclusive_sold: false,
    is_published: true,
    play_count: 142,
    like_count: 38,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "mock-2",
    beatmaker_id: "mock-producer",
    title: "Sous l'Eau",
    slug: "sous-leau",
    bpm: 95,
    key: "Cm",
    genre: "R&B",
    tags: ["chill", "melodic"],
    audio_preview_url: null,
    audio_full_url: null,
    cover_image_url: null,
    price_simple: 24.99,
    price_exclusive: 399.99,
    is_exclusive_sold: false,
    is_published: true,
    play_count: 87,
    like_count: 22,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "mock-3",
    beatmaker_id: "mock-producer",
    title: "Courant d'Air",
    slug: "courant-dair",
    bpm: 130,
    key: "F#m",
    genre: "Drill",
    tags: ["uk", "bounce"],
    audio_preview_url: null,
    audio_full_url: null,
    cover_image_url: null,
    price_simple: 34.99,
    price_exclusive: 599.99,
    is_exclusive_sold: false,
    is_published: true,
    play_count: 203,
    like_count: 56,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "mock-4",
    beatmaker_id: "mock-producer",
    title: "Écho",
    slug: "echo",
    bpm: 108,
    key: "Dm",
    genre: "Boom Bap",
    tags: ["oldschool", "sample"],
    audio_preview_url: null,
    audio_full_url: null,
    cover_image_url: null,
    price_simple: 19.99,
    price_exclusive: 299.99,
    is_exclusive_sold: false,
    is_published: true,
    play_count: 64,
    like_count: 15,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];
